//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public string Id_Calificacion { get; set; }
        public string Id_Curso { get; set; }
        public string Id_Materia { get; set; }
        public Nullable<double> Corte1 { get; set; }
        public Nullable<double> Corte2 { get; set; }
        public Nullable<double> Corte3 { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
