//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas
    {
        public int Id_Matricula { get; set; }
        public string Id_Estudiante { get; set; }
        public Nullable<System.DateTime> Fecha_inscripcion { get; set; }
        public string NoOrdenPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
