//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores
    {
        public string Id_Profesor { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
